apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-kiem
spec:
  selector:
    matchLabels:
      app: go-kiem
  template:
    metadata:
      labels:
        app: go-kiem
    spec:
      containers:
        - name: go-kiem
          image: gladium08/kiem:json
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
                memory: "128Mi"
                cpu: "250m"
            limits:
                memory: "248Mi"
                cpu: "500m"
      serviceAccount: kiem-service-account