apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-montu
spec:
  selector:
    matchLabels:
      app: go-montu
  template:
    metadata:
      labels:
        app: go-montu
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: go-montu
          image: 
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
                memory: "128Mi"
                cpu: "250m"
            limits:
                memory: "248Mi"
                cpu: "500m"
      serviceAccount: montu-service-account