apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiem-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
  namespace: default
rules:
  - apiGroups:
        - ""
        - extensions
        - apps
        - rbac.authorization.k8s.io
        - roles.rbac.authorization.k8s.io
        - authorization.k8s.io
    resources: ["*"]
    verbs:  ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-cluster-role-binding
subjects:
- namespace: default 
  kind: ServiceAccount
  name: kiem-service-account 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-cluster-role